import numpy as np

__all__ = [
    "DEFAULTS_INPUTS",
    "DEFAULT_MAXITER",
    "DEFAULT_FTOL",
    "DEFAULT_GTOL",
    "DEFAULT_MAXCOR",
    "DEFAULT_WEIGHT_SQUAREDFLUX",
    "DEFAULT_ITER_FREQ",
    "DEFAULT_SQUAREDFLUX_DEFINITION",
    "DEFAULT_NORMALIZED_OBJECTIVES",
    "DEFAULT_NTFS_TOTAL",
    "DEFAULT_NDIPOLES_TOR_TOTAL",
    "DEFAULT_NDIPOLES_POL_TOTAL",
    "DEFAULT_CURVE_CURVE_DISTANCE",
    "DEFAULT_TF_BASE_CURRENTS",
    "DEFAULT_DIPOLE_BASE_CURRENTS",
    "DEFAULT_SKIP_OUTBOARD_POL",
    "DEFAULT_SUPERELLIPSE_N",
    "DEFAULT_NQUADPOINTS",
    "DEFAULT_SURFACE_WOUT_S",
    "DEFAULT_FIX_DOFS",
    "DEFAULT_UNFIX_DOFS",
    "TINY",
    "TIMEZONE",
]

# Stage 2 defaults
DEFAULT_MAXITER = 1500
DEFAULT_FTOL = 1e-6
DEFAULT_GTOL = 1e-6
DEFAULT_MAXCOR = 300
DEFAULT_WEIGHT_SQUAREDFLUX = 1.0
DEFAULT_ITER_FREQ = 10

# Objectives defaults
DEFAULT_SQUAREDFLUX_DEFINITION = "local" # Local is preferred for the dipoles since their impact is so localized
DEFAULT_NORMALIZED_OBJECTIVES = True

# BiotSavart defaults
DEFAULT_NTFS_TOTAL = 16
DEFAULT_NDIPOLES_TOR_TOTAL = 2*DEFAULT_NTFS_TOTAL
DEFAULT_NDIPOLES_POL_TOTAL = 10
DEFAULT_CURVE_CURVE_DISTANCE = 0.03
DEFAULT_TF_BASE_CURRENTS = 80e3
DEFAULT_DIPOLE_BASE_CURRENTS = 150e3
DEFAULT_SKIP_OUTBOARD_POL = False
DEFAULT_SUPERELLIPSE_N = 4.0
DEFAULT_NQUADPOINTS = 128

# (Un)Fixed dof defaults
DEFAULT_FIX_DOFS = [
    "tf-currents",
]
DEFAULT_UNFIX_DOFS = [
]

# Surface defaults
DEFAULT_SURFACE_WOUT_S = 1.0

# Tiny
TINY = float(np.finfo(float).tiny)

# Timezone
from zoneinfo import ZoneInfo
TIMEZONE = ZoneInfo("America/New_York")

DEFAULTS_INPUTS = dict(
    maxiter=DEFAULT_MAXITER,
    ftol=DEFAULT_FTOL,
    gtol=DEFAULT_GTOL,
    maxcor=DEFAULT_MAXCOR,
    weight_squaredflux=DEFAULT_WEIGHT_SQUAREDFLUX,
    iter_freq=DEFAULT_ITER_FREQ,
    squaredflux_definition=DEFAULT_SQUAREDFLUX_DEFINITION,
    normalized_objectives=DEFAULT_NORMALIZED_OBJECTIVES,
    ntfs_total=DEFAULT_NTFS_TOTAL,
    ndipoles_tor_total=DEFAULT_NDIPOLES_TOR_TOTAL,
    ndipoles_pol_total=DEFAULT_NDIPOLES_POL_TOTAL,
    curve_curve_distance=DEFAULT_CURVE_CURVE_DISTANCE,
    tf_base_currents=DEFAULT_TF_BASE_CURRENTS,
    dipole_base_currents=DEFAULT_DIPOLE_BASE_CURRENTS,
    skip_outboard_pol=DEFAULT_SKIP_OUTBOARD_POL,
    superellipse_n=DEFAULT_SUPERELLIPSE_N,
    nquadpoints=DEFAULT_NQUADPOINTS,
    surface_wout_s=DEFAULT_SURFACE_WOUT_S,
    fix_dofs=DEFAULT_FIX_DOFS,
    unfix_dofs=DEFAULT_UNFIX_DOFS,
)
